FROM public.ecr.aws/lambda/go:latest

WORKDIR /lambda
COPY ./go.mod ./
RUN go mod download

RUN go build -o app main.go
COPY build/lambda /var/task/
RUN yum install lynx -yarn
COPY *.txt /var/task
COPY *.html /var/task

ENV _LAMBDA_SERVER_PORT=8080

CMD ["lambda"]

ENTRYPOINT [ "/var/task/lambda" ]
