AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - com.prepple.api::prepple-api
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  PreppleAPI:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.prepple.api.StreamLambdaHandler::handleRequest
      Runtime: java11
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Environment:
        Variables:
          PG_USERNAME: jayclark
          PG_PASSWORD: password1
          AWS_SAM_LOCAL: true
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  MyDevInterviewApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/ping'
    Export:
      Name: PreppleApi
